In [1]:
import numpy as np

In [11]:
matrix = [[7],[9],[6]]
d = matrix 
r = len(matrix)
c = len(matrix[0])
lt = 0      # right 
rt = 0      # bottom
lb = r -1  # up
rb = c -1  # left


l = []

print(r*c)

n = 0 
while n<(r*c):
    if len(l)==(r*c):
        break
        
    if n<(r*c):
        piv = lt
        for i in range(rb+1-piv):
            l.append(d[lt][piv])
            n = n + 1
            piv = piv + 1
        lt = lt +1
        print("27",n)
        
    if len(l)==(r*c):
        break

    if n<(r*c):
        piv = lt
        for i in range(lb-piv):
            l.append(d[piv][rb])
            n = n + 1
            piv = piv + 1
        print("38",n)
            
    if len(l)==(r*c):
        break
        
    if n<(r*c):
        piv = rb 
        for i in range(rb-lt+1):
            l.append(d[lb][piv] )
            n = n + 1
            piv = piv -1
        print("49",n)
        rb = rb -1   
        
    if len(l)==(r*c):
        break

    if n<(r*c):
        piv = lb
        for i in range(lb-lt+1):
            l.append(d[piv][lt-1])
            n = n + 1
            piv = piv -1
        print("61",n)
        lb = lb -1   

print(l)

3
27 1
38 2
49 2
61 4
[7, 9, 6, 9]


In [65]:
r = 3
c = 5
d = np.zeros((r,c))
# r = int(input("m: "))
# c = int(input("n: "))


lt = 0      # right 
rt = 0      # bottom
lb = r -1  # up
rb = c -1  # left

n = 1 

while n<= (r*c):
    if n<=(r*c):
        piv = lt
        for i in range(rb+1-piv):
            d[lt,piv] = n
            n = n + 1
            piv = piv + 1
        lt = lt +1

#         print(d) 
#         print("lt =",lt,"| rt =",rt,"| lb =",lb,"| rb =",rb)
#         print()


    if n<=(r*c):
        piv = lt
        for i in range(lb-piv):
            d[piv,rb] = n
            n = n + 1
            piv = piv + 1  

#         print(d) 
#         print("lt =",lt,"| rt =",rt,"| lb =",lb,"| rb =",rb)
#         print()

    if n<=(r*c):
        piv = rb 
        for i in range(rb-lt+1):
            d[lb,piv] = n
            n = n + 1
            piv = piv -1

        rb = rb -1   
#         print(d) 
#         print("lt =",lt,"| rt =",rt,"| lb =",lb,"| rb =",rb)
#         print()

    if n<=(r*c):
        piv = lb
        for i in range(lb-lt+1):
            d[piv,lt-1] = n
            n = n + 1
            piv = piv -1

        lb = lb -1   
print(d) 
print("lt =",lt,"| rt =",rt,"| lb =",lb,"| rb =",rb)
print()



[[ 1.  2.  3.  4.  5.]
 [12. 13. 14. 15.  6.]
 [11. 10.  9.  8.  7.]]
lt = 2 | rt = 0 | lb = 1 | rb = 3

